apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysqlService.port }}
      targetPort: {{ .Values.mysqlService.port }}
  type: {{ .Values.mysqlService.type }}

